---


- name: Install dependancies
  yum:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - httpd
    - git
    - python


- name: Create identifyme group
  group:
    name: "{{ identifyme_user }}"
    state: present
  become: true


- name: Add identifyme user
  user:
    name: "{{ identifyme_user }}"
    group: "{{ identifyme_user }}"
  become: true
