---


- name: Clear temp directory
  file:
    path: "{{ identifyme_temp_folder }}"
    state: "absent"
  become: true


- name: Create temp directory
  file:
    path: "{{ identifyme_temp_folder }}"
    state: "directory"
    mode: "0775"
    owner: "{{ identifyme_user }}"
    group: "{{ identifyme_user }}"
  become: true