---

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - git
    - python
    - python-pip

- name: Install pymongo via pip
  pip:
    name: pymongo